import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./app.css";
import AuthenticatorWrapper from "./AuthenticatorWrapper";
import "@aws-amplify/ui-react/styles.css";
import 'bootstrap/dist/css/bootstrap.min.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja" data-bs-theme="dark">
      <body>
        <nav className="navbar bg-body-tertiary">
          <div className="container-fluid">
            <span className="navbar-brand mb-0 h1">Shape Sync</span>
          </div>
        </nav>
        <AuthenticatorWrapper>
          <div className="container text-center">
            {children}
          </div>
        </AuthenticatorWrapper>
      </body>
    </html>
  );
}
